{{- $auth := .Values.auth | default dict }}
{{- if $auth.clientCA }}
apiVersion: v1
data:
  ca.crt: {{ $auth.clientCA }}
kind: Secret
metadata:
  name: client-ca
  namespace: zks-system
type: Opaque
{{- end }}
