url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-monitoring/66.7.1-rancher.10
commit: 794f66d61320ee7fa9aebd085141b2998dbee519
version: 105.2.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-monitoring-crd/66.7.1-rancher.10
      commit: 794f66d61320ee7fa9aebd085141b2998dbee519
doNotRelease: false
