url: https://github.com/rancher/ob-team-charts.git
subdirectory: charts/rancher-logging/4.10.0-rancher.6
commit: d9c8b66a67e954475ef877369d89f4043f1181a3
version: 107.0.0-rc.1
additionalCharts:
  - workingDir: charts-crd
    upstreamOptions:
      url: https://github.com/rancher/ob-team-charts.git
      subdirectory: charts/rancher-logging-crd/4.10.0-rancher.6
      commit: d9c8b66a67e954475ef877369d89f4043f1181a3
doNotRelease: false
